version: '3.8'

services:
  source:
    build:
      context: .
      dockerfile: Dockerfile.source
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  load-balancer-1:
    build:
      context: .
      dockerfile: Dockerfile.lb
    environment:
      - PYTHONUNBUFFERED=1
      - LB_ID=1
    depends_on:
      - source
    networks:
      - app-network

  load-balancer-2:
    build:
      context: .
      dockerfile: Dockerfile.lb
    environment:
      - PYTHONUNBUFFERED=1
      - LB_ID=2
    depends_on:
      - source
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 