FROM python:3.9-slim

WORKDIR /app

# Copia os requisitos e instala as dependências Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código fonte
COPY src/ /app/src/
COPY config/ /app/config/

# Torna os scripts de inicialização executáveis
RUN chmod +x /app/src/start_service.sh
RUN chmod +x /app/src/start_loadbalancer.sh

# Expõe a porta do load balancer
EXPOSE 8001

# Comando para iniciar o load balancer
CMD ["/app/src/start_loadbalancer.sh"] 