loadbalancer1:
  algorithm: round-robin
  host: localhost
  max_connections: 1000
  port: 8081
  services:
  - load-balancer-1:8083
  - load-balancer-1:8084
loadbalancer2:
  algorithm: round-robin
  host: localhost
  max_connections: 1000
  port: 8082
  services:
  - load-balancer-2:8085
  - load-balancer-2:8086
source:
  connection:
    retry_attempts: 3
    timeout: 5
  host: 0.0.0.0
  max_messages: 100
  port: 0
  request_rate: 30
  target: load-balancer-1
validation:
  feeding_stage:
    delay_between_messages: 1.0
    message_count: 10
  validation_stage:
    min_messages: 50
    timeout: 30
